---
- name: Setup a secure LAMP instance on CentOS 7
  hosts: webservers
  become: yes
  tasks:
    - name: "Ensure LAMP packages installed"
      yum:
        name: 
          - "http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm"
          - mysql-server
          - httpd
          - php
          - php-gd
          - php-mysqlnd
          - php-mbstring
          - php-process
          - php-xmlrpc
          - php-xml
          - libxslt
        state: present

    - name: "(Apache) [1/2]: Configure Apache2"
      lineinfile:
         dest: "/etc/httpd/conf/httpd.conf"
         regexp: "{{ item.regexp }}"
         line: "{{ item.line }}"
         backup: yes
      with_items:
        - {regexp: 'ServerSignature', line: 'ServerSignature Off'}
        - {regexp: 'ServerTokens', line: 'ServerTokens Prod'}
        - {regexp: 'TraceEnable', line: 'TraceEnable Off'}

    - name: "(Apache) [2/2]: Restarting Apache2 to apply changes..."
      service: 
        name: httpd
        state: restarted

    - name: "(MySQL) [1/2]: Configure MySQL (/etc/my.cnf)"
      lineinfile:
         dest: "/etc/my.cnf"
         regexp: "{{ item.regexp }}"
         line: "{{ item.line }}"
         backup: yes
      with_items:
        - {regexp: 'skip-show-database', line: 'skip-show-database'}

    - name: "(MySQL) [2/2]: Restarting MySQL to apply changes..."
      service: 
        name: mysqld
        state: restarted

    - name: "(PHP) [1/2]: Configure PHP (/etc/php.ini)"
      lineinfile:
         dest: "/etc/php.ini"
         regexp: "{{ item.regexp }}"
         line: "{{ item.line }}"
         backup: yes
      with_items:
        - {regexp: 'disable_functions', line: 'disable_functions = exec, system, shell_exec, passthru, popen, curl_exec, curl_multi_exec, parse_ini_file, show_source, proc_open, pcntl_exec'}
        - {regexp: 'expose_php', line: 'expose_php = Off'}
        - {regexp: 'display_errors', line: 'display_errors = Off'}
        - {regexp: 'track_errors', line: 'track_errors = Off'}
        - {regexp: 'html_errors', line: 'html_errors = Off'}
        
    - name: "(PHP) [2/2]: Restarting Apache2 to apply changes..."
      service: 
        name: httpd
        state: restarted